name: Remove old package versions
on:
  schedule:
    - cron:  '12 20 * * *'
  workflow_dispatch:
jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: purge packages
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: source-template
          user: dylanratcliffe
          token: ${{ secrets.CR_PAT }}
